WHITE_CARDS = [
'hello, my name is spongebob noodlepants',
'can somebody please tell me what the sound of one hand clapping is?',
'you have uno, it came free with your fucking xbox',
'the derivative of 2x is 2',
'Damn bro you frying chicken in there? You piss real loud and i think thats pretty cool',
'new phone, who dis?',
'i was kicked out of costco for stealing all the free samples',
"i dont need to call a doctor, i asked my Facebook mom's group",
"People who live",
"No Taylor, cannot just shake it off",
"If i think therefore I am, then i shall be Obama",
"Honey, you need more than a hairnet to hold in that beehive",
"You will play Capture the Flag and you will like it",
"It has meat, it has noodles. And that's all you need to know.",
"And this is the stadium where Shakira first sung her hit song, Waka Waka",
"It's peanut butter jelly time.",
"Damn bro you got arms like wii sports character.",
"I am blue da ba di da ba die",
"We could party like it's 1999 but then we wouldn't have snapchat",
"..this leads to King Bach pulling out a comically large spoon",
"Father I cannot click the book",
"People say nothing is impossible, but i do nothing everyday",
"I’m sick of following my dreams, man. I’m just going to ask where they’re going and hook up with ’em later",
"I feel in today's time, you are truly successful if a meme is based on you.",
"I refuse to join any club that would have me as a member.",
"All right everyone, line up alphabetically according to your height",
"My grandmother started walking five miles a day when she was sixty. She's ninety-seven now, and we don't know where the hell she is.",
"You're only as good as your last haircut.",
"You're only as good as your last haircut.",
"What's another word for Thesaurus?",
"A foolish man shares his problems. A wise one shares his memes",
"Everything I like is either illegal, immoral or fattening",
"My face looks like a wedding-cake left out in the rain.",
"I am swift as a gazelle",
"I don’t suffer from insanity, I enjoy every minute of it.",
"After millions of years of evolution, you’re kind of a disappointment",
"Fart when people hug you. You’ll make them feel strong.",
"He who laughs last is a bit of a slow thinker.",
"Clothes make the man. Naked people have little or no influence in society.",
"I would love to stand here and talk with you—but I’m not going to.",
"Ben, you gotta treat a woman like a car",
"Help me, Obi-Wan Kenobi. My airfryer broke.",
"Do. Or do not. There is no try.",
"Those brain cells cannot contain much brain.",
"Now, young Skywalker, you will die.",
"Our first rocket has one goal. UP!",
"Fear is the path to the dark side",
"Enemy spotted, moving to engage",
"Power! Unlimited power!",
"You were my brother, Anakin. I loved you.",
"It is time we foresake our customs. And run straight past TSA",
"I am no Jedi, but i do make good guesses",
"I’m king of the world!",
"Where we’re going, we don’t need roads!",
"Hakuna Macaca… it means no shit!",
"There’s no “we” in fries.",
"When nothing goes right, go left.",
"I always prefer my puns to be intended.",
"My hobbies are breakfast, lunch, and dinner.",
"You should try to watch more sunsets than Netflix.",
"Wine + dinner = winner",
"After Tuesdays, even the calendar goes WTF.",
"The first 5 days after the weekend are the hardest.",
"I drink to make other people more interesting.",
"Be a cupcake in a world of muffins.",
"Chocolate never asks me any questions, chocolate understands me.",
"Life is too short to wear boring socks.",
"Yoo! He just hit the whip AND nae ane at the same time!",
"8 p.m. is the new midnight!",
"Love, it sustains you. It’s like oatmeal.",
"Every time you talk, I hear that sound that plays when Pac-Man dies.",
"I asked them if they wanted to embarrass you, and they instantly said yes.",
"The English language cannot fully capture the depth and complexity of my thoughts, so I’m incorporating emojis into my speech to better express myself. Winky face.",
"I just negotiated my baby girls down from a pony to a hamster. Little fools.",
"I wasn't hurt that badly. The doctor said all my bleeding was internal. That's where the blood's supposed to be.",
"If I die, turn my tweets into a book.",
"Anyone over the age of six celebrating a birthday should go to hell.",
"Right now, what I need, is for you to climb down out of my ass. Can you do that?",
"Yeah, Mr. White! Yeah, Science!",
"The moral of the story is…I chose a half measure when I should have gone all the way",
"You’re the smartest guy I’ve ever met. And you’re too stupid to see...",
"The fun’s over. From here on out, I’m Mr. Low Profile. Just another douche bag with a job and three pairs of Dockers.",
"I’m not saying it’s not bad. It’s bad. But it could be worse.",
"Did you know that there’s an acceptable level of rat turds that can go into candy bars?",
"Darth Vader had responsibilities. He was responsible for the Death Star.",
"I hide in plain sight, same as you.",
"Say my name.",
"I am not in danger, I am the danger.",
"I did it for me. I liked it. I was good at it. And, I was really…I was alive.",
"The ability to speak does not make you intelligent",
"Now, witness the power of this fully operational battle station.",
"I see dead people",
"I used to think my life was a tragedy, but now I realize it’s a comedy.",
"If you’re good at something, never do it for free.",
"Wait ’til they get a load of me.",
"I won’t kill you because you’re just too much fun.",
"A joke a day keeps the gloom away!",
"Some people want to see you fail. Disappoint them!",
"Enjoy being lazer burned.",
"He stared down his demons and he conquered them.",
"I should have never trusted the flawed calculations of a clone",
"You couldn’t just sit this one out? Let us kill the President.",
"It’s kind of like, peeing your pants on purpose.",
"I need something to punch.",
"Yo it says in the bible: 'thy suck thy dick' it does.",
"I don’t know who you are but it’s time to go.",
"My god there's blood everywhere!",
"When your wife's boyfriend brings home chipotle",
"Uwu? are you kidding me? At a my parents funeral?? ",
"Road work ahead? Uh yeah, I sure hope it does.",
"Happy Crimus.....It's crismun....Merry crisis.  Merry Chrysler.",
"I spilled lipstick in your Valentino bag. ",
"Hurricane Katrina? More like Hurricane Tortilla.",
"When will you learn that your actions have consequences?",
"How much did you pay for that taco?",
"BOOM BOOM BOOM BOOM. I want you in my room..",
"Get to Del Taco. They got a new thing called freeshavaca-do",
"I'm outside your house waiting for you to come out",
"Bitch i already beat this game on legendary. I know where the fucking ice cream is.",
"Yo, how much money do you have? 65 cents. Aye, you know what that means?",
"And they were roommates. Mah God, they were roommates.",
"Look at all those chickens!",
"What are thoseeeeee?",
"I sneezed, oh, what, am I not allowed to sneeze?",
"Jared, can you read number 23 for the class?",
"I’m Jared, I’m 19 and I never  learned how to read.",
"Today’s forecast, we can clearly see that somebody got me all annoyed!",
"What’s 9 plus 10?",
"So you just gonna bring me a birthday gift on my birthday to my birthday party on my birthday with a birthday gift?",
"Hi, welcome to Chili's.",
"My name is Michael with a B and I’ve been afraid of insects my entire life",
"It's Wednesday, my dudes. The weekend is here.",
"I am shooketh. I like do the shaky dance.",
"I smell like beef.",
"Welcome to Bible Study. We’re all children of Jesus.",
"This is the dollar store, how good can it be?",
"I’m sorry I didn’t see you there. I was too busy blocking out the haters.",
"Do you guys even listen to Drake?",
"I can’t sleep, because of that video.",
"You know i'm about to say it. I don't care that you broke your elbow",
"That was legitness.",
"I’m just cooking pizza and not baking one.",
"Two shots of vodka",
"I can't swim!",
"Deez nuts, ha got em!",
"Why are you running, why are you running? ",
"Wait a minute, who are you?",
"Are you an alien?",
"I am gonna get in trouble if I keep talking.",
"I’m a bad girl, you can’t kill me.",
"I wanna be a cowboy baby.",
"Scalpe. Tweesers. Waffle iron",
"This edible ain't shit!",
"Two guys, chillin' in a hot tub, 5 feet apart",
"I don’t have enough money for chicken nuggets.",
"Iridocyclitis.",
"Come get y’all juice.",
"All women... are queens.",
"If she breathes, shes a thot!",
"Aren't you hot in that outfit?",
"Who's Gannondorf?",
"Eyebrows on fleek.",
"If you're homeless, just buy a house.",
"I am too lazy to be lazy",
"I’m in my mum’s car. Broom broom!",
"Sometimes when I close my eyes, I can’t see.",
"Scanning for the ice scream..",
"I Giorno Giovana have a dream",
"If you lift heavy stone, sad head voice go quiet",
"Call me when you can, we need more fiber",
"Okay google, what's the farthest place from france",
"I am once again asking you to hit that stanky leg.",
"Fuck it, i'm killing the chicken",
"Why do you sound like luigi?",
"It's not pink, it's lightish red!",
"I'm killing you! Like shooting you in the head!",
"I’m late for an important meeting with the slugs",
"Ain't nothing like looking at Don Cheedle's head",
"Cancel Christmas! We're opening a coal mine",
"I present to you... Mega Hitler!",
"You look like George Washington's teeth",
"I might be cringe. But I am free.",
"Where is the joke? It's just a picture of a horse!",
"Joe Biden, Clearly can't handle THIS badonkadonk",
"Why did you just say 'that's cool'? I just told you we're going bankrupt!",
"I skinned this bannana alive",
"Check out the big brains on Brad",
"Look at you being a little scientist. Making observations.",
"As an officer of the law I can assure you that I ain't a cop.",
"You look like you have dumb bitch syndrome.",
"I am weak, but also still weak",
"I wet the bed untill i was 14 years old",
"Got pulled over for doing 100 in a 40",
"Animals are yummy in Elmos tummy",
"I cant wait to kick your ass!",
"What are you bringing for co-workersgiving?",
"We got food at the house!",
"I am commiting tax fraud",
"You're under arrest for tax fraud",
"Can I get a large number 2?",
"I'm not gonna stand here and listen to you bad mouth the greatest democracy the world has ever known.",
"I'm not fat, I'm just getting ready for dad bod season.",
"The time is currently onetey one o clock",
"You like my hair? Gee, thanks, just bought it.",
"We gonna party like it's your birthday.",
"It ain’t no fun if the homies can’t have none.",
"Last night I saw you in my dreams",
"Don't criticize what you can't understand.",
"Mama, just killed a man",
"Yesterday, all my troubles seemed so far away",
"Hello darkness my old friend",
"I read the news today, oh boy",
"It's Britney, bitch.",
"When I was a young boy, I shit my pants",
"There must be some kinda way out of here",
"Let's get down to business",
"Oh, my, God, Becky. Look at her butt",
"Hello? Is there anybody in there?",
"We come from the land of the ice and snow",
"I could never live without MountainDew Baja Blast",
"ARE YE READY, KIDS?",
"There is a house in New Orleans..",
"Carry on my wayward son",
"When I find myself in times of trouble, Mother Mary comes to me",
"Do you remember, the 21st night of September?",
"Is this the real life? Is this just fantasy?",
"Go shawty, it's your birthday..",
"Making my way downtown..",
"Just a small town girl, living in a lonely world.",
"Why are there corpses in this windmill?",
"Some people call me the space cowboy...",
"you can tell by the way I use my walk",
"I am sick of these mother fucking snakes..",
"Don't call it a comeback, I been here for years.",
"You may say I’m a liar, but I’m a truther",
"All you need is blood.",
"Love me or hate me, you gotta admit I got big balls!",
"Why is there poo in pants?!",
"Feeling good living better.",
"They say good things come to those who wait, so imma be at least an hour late.",
"These are the days we’ll never forget.",
"Honey, can you open the garage door?",
"To appreciate the sun, you gotta know what rain is.",
"Give me the beat boys and free my soul.",
"Listen to the silent trees.",
"I am the lorax and I speak for the trees!",
"What are you looking at?",
"Pen Pineapple Apple Pen",
"Yoga is a fad that wont go away",
"My sprit animal is a Snorlax",
"",
"",
"",
"",
"",
"",
"",
"",
]



BLACK_CARDS = [
'Valley Girl',
'Baiuu',
'Redneck'
'Whisper',
'Surfer',
'Obama',
'Grandma',
'Grandpa',
'Robot',
'Helium',
'Pirate',
'Italian',
'Elmo',
'Chicken',
'Russian',
'German',
'Spanish',
'Irish',
'Scottish',
'British',
'New Yorker',
'Jamacan',
'French',
'Vampire',
'Batman',
'Australian',
'Indian',
'Caveman',
'Nerd',
'Greaser',
'Boston',
'Punk',
'Old Timey',
'Thespian',
'Hulk Hogan',
'Gym Bro',
'Idiot',
'Scared',
'Happy',
'Sad',
'Angry',
'Sleepy',
'Yoda',
'Lois Griffin',
'Joe Swanson',
'Ganster',
'Arnold Schwarzenegger',
'Kermit the Frog',
'Cholo',
'Southern',
'Minesota',
'Kind',
'Scooby Doo',
'Shaggy',
'Hank Hill',
'Napoleon Dynamite',
'Bill Cosby',
'Shrek',
'Squidward',
'Fat Albert',
'Bender',
'Stewie',
'Eric Cartman',
'Spongebob',
'Patrick Star',
'Texas',
'Mickey Mouse',
'Goofy',
'Bugs Bunny',
'Elvis',
'Tall Ed',
'Rolf',
'Morty',
'Rick',
'Dr Doofenshmirtz',
'Mario',
'Luigi',
'Toad',
'Forest Gump',
'Gollum',
'Gandalf',
'Hagrid',
'Dobby',
'Palpatine',
'C3P0',
'Elmer Fudd',
'Wario',
'Skipper',
'Minion',
'Sid',
'Mort',
'Mr T',
'Joker',
'Bane',
'Stitch',
]

